// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phmmugoymwfydbwgbvbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobW11Z295bXdmeWRid2didmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM2OTU3MTMsImV4cCI6MjA5OTI3MTcxM30.8sTQlVoxFxSROTAdG4uIdeacOw76MIWAHao-uSS1D2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});